import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { BottomNav } from "@/components/navbar/Navbar";
import Providers from "@/components/Providers";
import "./globals.css";
import AddEntry from "@/components/AddEntry/AddEntry";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <Providers>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased mb-20`}
      >
        <main className="mx-0 my-0 md:mt-[3%] md:mr-[25%] md:mb-[5%] md:ml-[25%]">
          {children}
        </main>
        <AddEntry/>
        <BottomNav />
        
      </body>
      </Providers>
    </html>
  );
}
